CHAPTERS['ch2']={
  title:'第二章 消えた灯り',
  scenes:{
    start:{
      lines:[
        {c:'narrator',t:'店主が気絶していた事実に、全員が動揺していた。'},
        {c:'chibabu',t:'まず状況を整理しよう。停電、スマホの紛失、そして気絶した店主。'},
        {c:'yocchin',t:'偶然にしちゃ出来すぎてるよな。'},
        {c:'nobun',t:'つまり、誰かが意図的にやったってことか？'},
        {c:'narrator',t:'沈黙が流れた。'}
      ],
      choice:{
        prompt:'ちばぶの提案に賛成するか？',
        right:{label:'賛成する',next:'agree'},
        left:{label:'反対する',next:'disagree'}
      }
    },
    agree:{
      lines:[
        {c:'chibabu',t:'よし、まず出入り口を確認しよう。誰も出入りしていないか。'},
        {c:'edimarcy',t:'俺が入口を見てくる。'},
        {c:'narrator',t:'エディマーシーが入口に向かった。'},
        {c:'edimarcy',t:'おい、ドアが開かねえぞ。外から何かで塞がれてる。'},
        {c:'ochipu',t:'は？閉じ込められてるってことか！？'}
      ],
      next:'locked'
    },
    disagree:{
      lines:[
        {c:'yukkin',t:'整理なんかいいから、まず逃げようぜ。'},
        {c:'debucorn',t:'そうだな。入口から出よう。'},
        {c:'narrator',t:'全員が入口に殺到するが。'},
        {c:'edimarcy',t:'ドアが開かない。外から塞がれてる。'},
        {c:'ochipu',t:'嘘だろ！？'}
      ],
      next:'locked'
    },
    locked:{
      lines:[
        {c:'narrator',t:'居酒屋「滝下」は、完全に密室と化していた。'},
        {c:'katopan',t:'窓はどうだ？'},
        {c:'chibabu',t:'この店は地下にある。窓はない。'},
        {c:'yocchin',t:'つまり、犯人はこの中にいるってことか。'},
        {c:'narrator',t:'8人の幼馴染が、互いを疑い始めた。'}
      ],
      choice:{
        prompt:'誰が怪しいと思う？',
        up:{label:'おちぷーが怪しい',next:'suspect_ochi'},
        down:{label:'よっちんが怪しい',next:'suspect_yochi'},
        right:{label:'まだ判断しない',next:'no_judge'},
        left:{label:'全員怪しい',next:'all_suspect'}
      }
    },
    suspect_ochi:{
      lines:[
        {c:'yukkin',t:'おちぷー、お前一番最初に来てたよな。何か仕込んだんじゃねえの？'},
        {c:'ochipu',t:'は！？俺じゃねえよ！ふざけんな！'},
        {c:'ochipu',t:'大体、俺がこんな面倒なことするわけねえだろ！'},
        {c:'narrator',t:'おちぷーは必死に否定した。その必死さが、逆に怪しく映った。'}
      ],
      next:'chapter_end'
    },
    suspect_yochi:{
      lines:[
        {c:'nobun',t:'よっちん、お前さっき儲け話がどうとか言ってたな。'},
        {c:'yocchin',t:'え？あれはただの冗談だって。まさか俺を疑ってんの？'},
        {c:'debucorn',t:'お前の冗談は冗談に聞こえねえんだよ。'},
        {c:'narrator',t:'よっちんは苦笑いを浮かべた。暗闇で誰にも見えなかったが。'}
      ],
      next:'chapter_end'
    },
    no_judge:{
      lines:[
        {c:'chibabu',t:'冷静だな。まだ情報が少なすぎる。'},
        {c:'katopan',t:'そうだ。まずは店主が目を覚ますのを待とう。'},
        {c:'narrator',t:'しかし、店主は一向に目を覚まさなかった。'}
      ],
      next:'chapter_end'
    },
    all_suspect:{
      lines:[
        {c:'yukkin',t:'全員怪しいって、俺たちの中に犯人がいるってことか。'},
        {c:'edimarcy',t:'まあ、外から鍵かけられてる時点でな。'},
        {c:'debucorn',t:'いや待て、それだと犯人は外にいるんじゃねえか？'},
        {c:'chibabu',t:'鍵をかけてから別の入口で戻った可能性もある。'},
        {c:'narrator',t:'議論は堂々巡りを始めた。'}
      ],
      next:'chapter_end'
    },
    chapter_end:{
      lines:[
        {c:'narrator',t:'その時、奥の厨房から金属音が響いた。'},
        {c:'debucorn',t:'今の音、包丁が落ちた音だ。間違いない。'},
        {c:'narrator',t:'全員が息を呑んだ。この中の誰かが、暗闇で動いている。'},
        {c:'narrator',t:'第二章 完'}
      ],
      end:true
    }
  }
};