CHAPTERS['ch1']={
  title:'第一章 暗闇の声',
  scenes:{
    start:{
      lines:[
        {c:'narrator',t:'停電から数分が経った。誰も動けずにいた。'},
        {c:'ochipu',t:'おい、誰か懐中電灯とか持ってないのかよ！'},
        {c:'chibabu',t:'人間の目が暗闇に慣れるまで約30分かかる。まずは落ち着こう。'},
        {c:'yukkin',t:'待てよ。なんか変な音しないか？'},
        {c:'narrator',t:'奥の方から、かすかな物音が聞こえる。'}
      ],
      choice:{
        prompt:'物音を調べに行くか？',
        right:{label:'調べに行く',next:'investigate'},
        left:{label:'じっとしている',next:'stay'}
      }
    },
    investigate:{
      lines:[
        {c:'yukkin',t:'俺が見てくるぜ。'},
        {c:'ochipu',t:'お、おう。気をつけろよ。俺はここで待つ。'},
        {c:'narrator',t:'ゆっきんが暗闇の中、手探りで奥へ進んでいく。'},
        {c:'yukkin',t:'うわっ！おい、何か倒れてるぞ！'},
        {c:'debucorn',t:'何だと！？大丈夫か！？'}
      ],
      choice:{
        prompt:'全員で確認しに行くか？',
        right:{label:'全員で行く',next:'all_go'},
        left:{label:'誰か一人を送る',next:'send_one'}
      }
    },
    stay:{
      lines:[
        {c:'nobun',t:'変に動かない方がいい。暗闇で怪我するぞ。'},
        {c:'yocchin',t:'そうそう。じっとしてれば電気も戻るって。'},
        {c:'narrator',t:'しかし1分、2分と経っても復旧しない。'},
        {c:'narrator',t:'そして突然、悲鳴が響いた。'},
        {c:'katopan',t:'今の声、厨房の方じゃないか！？'}
      ],
      choice:{
        prompt:'悲鳴の方へ向かうか？',
        right:{label:'向かう',next:'all_go'},
        left:{label:'まだ動かない',next:'wait_more'}
      }
    },
    wait_more:{
      lines:[
        {c:'ochipu',t:'い、いや動くなよ。罠かもしれないだろ。'},
        {c:'yukkin',t:'罠って何だよ。お前ビビりすぎだろ。'},
        {c:'narrator',t:'再び悲鳴。今度はもっと近い。'},
        {c:'edimarcy',t:'もう待てねえ。行くぞ。'}
      ],
      next:'all_go'
    },
    send_one:{
      lines:[
        {c:'ochipu',t:'誰か一人だけ行けよ。俺はここで見張ってるから。'},
        {c:'nobun',t:'しょうがねえな。俺が行くよ。'},
        {c:'narrator',t:'のぶんが暗闇の奥へ消えていく。しばらくして。'},
        {c:'nobun',t:'おい！やばいぞ！全員来てくれ！'}
      ],
      next:'all_go'
    },
    all_go:{
      lines:[
        {c:'narrator',t:'全員が手探りで奥へ向かう。'},
        {c:'edimarcy',t:'足元気をつけろ。ガラスの破片がある。'},
        {c:'chibabu',t:'ガラス？何かが割れたのか。'},
        {c:'narrator',t:'そこで一同は信じられないものに触れた。'},
        {c:'debucorn',t:'こ、これ…人じゃねえか！？動かないぞ！'}
      ],
      next:'discovery'
    },
    discovery:{
      lines:[
        {c:'katopan',t:'待て、脈を見る。脈はある。気絶してるだけだ。たぶん。'},
        {c:'chibabu',t:'たぶんって何だよ。'},
        {c:'narrator',t:'倒れていたのは店の主人だった。'},
        {c:'narrator',t:'そしてその手には、何かのメモが握られていた。'},
        {c:'yocchin',t:'メモ？暗くて読めないけど、紙の感触はするな。'},
        {c:'ochipu',t:'触るなよ！指紋がつくだろ！'},
        {c:'yukkin',t:'お前が一番怪しいんだよ。'},
        {c:'narrator',t:'暗闇の中、疑惑の種が静かに芽吹き始めた。'},
        {c:'narrator',t:'第一章 完'}
      ],
      end:true
    }
  }
};