const Chapter1Script = [
  // ===== 導入 =====
  {type:'text',character:'ナレーション',
    text:'だいいっしょう、くらやみのはじまり。',
    displayText:'第一章　暗闇の始まり'},
  {type:'silence',duration:1500},
  {type:'text',character:'ナレーション',
    text:'ここからさきはかんぜんなくらやみのせかいです。がめんにはなにもうつりません。',
    displayText:'ここから先は完全な暗闇の世界です。画面には何も映りません。'},
  {type:'text',character:'ナレーション',
    text:'めをつぶってもあそべます。おんせいとふりっくそうさだけですすみます。',
    displayText:'目をつぶっても遊べます。音声とフリック操作だけで進みます。'},
  {type:'text',character:'ナレーション',
    text:'たっぷするといまのおんせいをすきっぷします。せんたくしはふりっくのうえしたひだりみぎでえらびます。ながおしでめにゅーにもどります。',
    displayText:'タップすると今の音声をスキップします。選択肢はフリックの上下左右で選びます。長押しでメニューに戻ります。'},
  {type:'text',character:'ナレーション',
    text:'でははじめましょう。',
    displayText:'では、始めましょう。'},
  {type:'silence',duration:2000},

  // ===== 停電直後 =====
  {type:'text',character:'ナレーション',
    text:'やみ。なにもみえない。めをあけてもとじてもおなじくらやみ。',
    displayText:'闇。何も見えない。目を開けても閉じても同じ暗闇。'},
  {type:'silence',duration:1000},
  {type:'text',character:'ゆっきん',
    text:'おいなんだこれ。でんききえたぞ。',
    displayText:'おいなんだこれ。電気消えたぞ。'},
  {type:'text',character:'おちぷー',
    text:'うわあっ!',
    displayText:'うわあっ！'},
  {type:'text',character:'おちぷー',
    text:'まじかよなにもみえねえ。こわいこわいこわい。',
    displayText:'マジかよ何も見えねえ。怖い怖い怖い。'},
  {type:'text',character:'ちばぶ',
    text:'おちついて。ていでんはだいたいすうふんでふっきゅうする。',
    displayText:'落ち着いて。停電はだいたい数分で復旧する。'},
  {type:'text',character:'デブコーン',
    text:'おれのりょうりがまだとちゅうなんだけど。',
    displayText:'俺の料理がまだ途中なんだけど。'},
  {type:'text',character:'かとぱん',
    text:'だれかけがしたやついないか。こえだせ。',
    displayText:'誰か怪我した奴いないか。声出せ。'},

  // ===== 安否確認 =====
  {type:'text',character:'ナレーション',
    text:'くらやみのなかでぜんいんがこえをだしはじめる。',
    displayText:'暗闇の中で全員が声を出し始める。'},
  {type:'text',character:'ゆっきん',
    text:'よしじゅんばんになまえいっていこう。おれゆっきん。',
    displayText:'よし順番に名前言っていこう。俺ゆっきん。'},
  {type:'text',character:'おちぷー',text:'おおちぷー。',displayText:'お、おちぷー。'},
  {type:'text',character:'ちばぶ',text:'ちばぶ。',displayText:'ちばぶ。'},
  {type:'text',character:'デブコーン',text:'でぶこーん。',displayText:'デブコーン。'},
  {type:'text',character:'のぶん',text:'のぶん。',displayText:'のぶん。'},
  {type:'text',character:'よっちん',text:'よっちん。',displayText:'よっちん。'},
  {type:'text',character:'かとぱん',text:'かとぱん。',displayText:'かとぱん。'},
  {type:'text',character:'エディマーシー',text:'えでぃまーしー。',displayText:'エディマーシー。'},
  {type:'silence',duration:1500},

  // ===== 9つ目の声 =====
  {type:'text',character:'ナレーション',
    text:'しずかなこえがもうひとつきこえた。',
    displayText:'静かな声がもう一つ聞こえた。'},
  {type:'silence',duration:800},
  {type:'text',character:'ナレーション',
    text:'きゅう。',
    displayText:'「九」'},
  {type:'silence',duration:1500},
  {type:'text',character:'ナレーション',
    text:'だれかがきゅうといった。はちにんしかいないはずなのに。',
    displayText:'誰かが「九」と言った。八人しかいないはずなのに。'},
  {type:'text',character:'ゆっきん',
    text:'おいいまだれかもうひとりこえださなかったか。',
    displayText:'おい今誰かもう一人声出さなかったか。'},
  {type:'text',character:'おちぷー',
    text:'えっうそだろ。きのせいだってきのせいだよな。',
    displayText:'え、嘘だろ。気のせいだって。気のせいだよな。'},

  // ===== 選択肢1 =====
  {type:'choice',
    text:'もういちどかぞえますか。',
    displayText:'もう一度数えますか？',
    choices:[
      {text:'もういちどぜんいんでなまえをいう',displayText:'もう一度全員で名前を言う',jump:'recount'},
      {text:'きのせいだとおもってむしする',displayText:'気のせいだと思って無視する',jump:'ignore_nine'}
    ]
  },

  // ===== もう一度数える =====
  {type:'text',label:'recount',character:'ナレーション',
    text:'もういちどじゅんばんになまえをよんでいく。',
    displayText:'もう一度順番に名前を呼んでいく。'},
  {type:'text',character:'ゆっきん',text:'ゆっきん。いち。',displayText:'ゆっきん。一。'},
  {type:'text',character:'おちぷー',text:'おちぷー。に。',displayText:'おちぷー。二。'},
  {type:'text',character:'ちばぶ',text:'ちばぶ。さん。',displayText:'ちばぶ。三。'},
  {type:'text',character:'デブコーン',text:'でぶこーん。よん。',displayText:'デブコーン。四。'},
  {type:'text',character:'のぶん',text:'のぶん。ご。',displayText:'のぶん。五。'},
  {type:'text',character:'よっちん',text:'よっちん。ろく。',displayText:'よっちん。六。'},
  {type:'text',character:'かとぱん',text:'かとぱん。なな。',displayText:'かとぱん。七。'},
  {type:'text',character:'エディマーシー',text:'えでぃまーしー。はち。',displayText:'エディマーシー。八。'},
  {type:'silence',duration:2000},
  {type:'text',character:'ナレーション',
    text:'きゅうにんめのこえはきこえなかった。しかしだれかのいきづかいがすぐちかくにある。',
    displayText:'九人目の声は聞こえなかった。しかし誰かの息遣いがすぐ近くにある。'},
  {type:'text',character:'ちばぶ',
    text:'おんきょうがくてきにいうとへやのなかのおとのはんしゃでにんずうがおおくきこえることはありえる。',
    displayText:'音響学的に言うと部屋の中の音の反射で人数が多く聞こえることはあり得る。'},
  {type:'text',character:'よっちん',
    text:'ほんとうにそうかな。おれにはたしかにきゅうにんめのこえがきこえたけどな。',
    displayText:'本当にそうかな。俺には確かに九人目の声が聞こえたけどな。'},
  {type:'flag',key:'recount',value:true},
  {type:'jump',target:'floor_sound'},

  // ===== 無視する =====
  {type:'text',label:'ignore_nine',character:'ナレーション',
    text:'きのせいだとおもうことにした。しかしむねのおくにいやなよかんがのこる。',
    displayText:'気のせいだと思うことにした。しかし胸の奥に嫌な予感が残る。'},
  {type:'text',character:'ゆっきん',
    text:'まあいいか。それよりでんきなんとかなんねえのか。',
    displayText:'まあいいか。それより電気なんとかなんねえのか。'},
  {type:'text',character:'エディマーシー',
    text:'ぶれーかーさがしてみるか。かべぞいにいけばあるだろ。',
    displayText:'ブレーカー探してみるか。壁沿いに行けばあるだろ。'},
  {type:'flag',key:'recount',value:false},
  {type:'jump',target:'floor_sound'},

  // ===== 床の音 =====
  {type:'text',label:'floor_sound',character:'ナレーション',
    text:'そのときゆかをなにかがはうおとがきこえた。',
    displayText:'その時、床を何かが這う音が聞こえた。'},
  {type:'silence',duration:600},
  {type:'text',character:'ナレーション',
    text:'ずるっ、ずるっ、ずるっ。',
    displayText:'ずるっ……ずるっ……ずるっ……'},
  {type:'text',character:'おちぷー',
    text:'ひいっ!',
    displayText:'ひいっ！'},
  {type:'text',character:'おちぷー',
    text:'なんだいまのおと。だれかうごいたのか。',
    displayText:'なんだ今の音。誰か動いたのか。'},
  {type:'text',character:'デブコーン',
    text:'おれじゃねえ。おれはうごいてねえ。',
    displayText:'俺じゃねえ。俺は動いてねえ。'},
  {type:'text',character:'のぶん',
    text:'おれもうごいてない。',
    displayText:'俺も動いてない。'},

  // ===== 選択肢2 =====
  {type:'choice',
    text:'ゆかのおとのしょうたいをさぐりますか。',
    displayText:'床の音の正体を探りますか？',
    choices:[
      {text:'てをのばしてゆかをさわる',displayText:'手を伸ばして床を触る',jump:'touch_floor'},
      {text:'ぜったいにうごかない',displayText:'絶対に動かない',jump:'dont_move'}
    ]
  },

  // ===== 床を触る =====
  {type:'text',label:'touch_floor',character:'ナレーション',
    text:'てをのばす。ゆかにふれる。つめたい。そしてぬるいえきたいがゆびにつく。',
    displayText:'手を伸ばす。床に触れる。冷たい。そしてぬるい液体が指につく。'},
  {type:'text',character:'ナレーション',
    text:'それがなんなのかくらやみではわからない。ただなまぐさいにおいがする。',
    displayText:'それが何なのか暗闇では分からない。ただ生臭い匂いがする。'},
  {type:'text',character:'のぶん',
    text:'あわりい。おれのつりのくーらーぼっくすからみずがもれてるかも。',
    displayText:'あ、悪い。俺の釣りのクーラーボックスから水が漏れてるかも。'},
  {type:'text',character:'ちばぶ',
    text:'さかなのたいえきのにおいだね。こさばならそういうにおいがする。',
    displayText:'魚の体液の匂いだね。小魚ならそういう匂いがする。'},
  {type:'flag',key:'touched_floor',value:true},
  {type:'jump',target:'scream'},

  // ===== 動かない =====
  {type:'text',label:'dont_move',character:'ナレーション',
    text:'うごかない。いっさいうごかない。くらやみのなかでじっといきをころす。',
    displayText:'動かない。一切動かない。暗闇の中でじっと息を殺す。'},
  {type:'text',character:'ナレーション',
    text:'はうおとがすこしずつちかづいてくる。あしもとのすぐちかくまで。',
    displayText:'這う音が少しずつ近づいてくる。足元のすぐ近くまで。'},
  {type:'text',character:'ナレーション',
    text:'そしておとがやんだ。',
    displayText:'そして、音が止んだ。'},
  {type:'flag',key:'touched_floor',value:false},
  {type:'jump',target:'scream'},

  // ===== 悲鳴 =====
  {type:'silence',label:'scream',duration:800},
  {type:'text',character:'おちぷー',
    text:'ぎゃああああっ!',
    displayText:'ぎゃああああっ！'},
  {type:'text',character:'ナレーション',
    text:'だれかがさけんだ。あしをつかまれたと。しかしだれのこえなのかわからない。',
    displayText:'誰かが叫んだ。足を掴まれたと。しかし誰の声なのか分からない。'},
  {type:'text',character:'ナレーション',
    text:'くらやみのなかでこえがとびかう。',
    displayText:'暗闇の中で声が飛び交う。'},
  {type:'text',character:'ゆっきん',
    text:'おいだれだいまの。だれがさけんだ。',
    displayText:'おい誰だ今の。誰が叫んだ。'},
  {type:'text',character:'かとぱん',
    text:'おれじゃない。おれのとなりのやつじゃないか。',
    displayText:'俺じゃない。俺の隣の奴じゃないか。'},
  {type:'text',character:'よっちん',
    text:'おれでもないぜ。てかおれのとなりにだれがいるかもわかんねえんだけど。',
    displayText:'俺でもないぜ。てか俺の隣に誰がいるかも分かんねえんだけど。'},

  // ===== 選択肢3（4択） =====
  {type:'choice',
    text:'どうしますか。',
    displayText:'どうしますか？',
    choices:[
      {text:'さけんだにんげんをさがす',displayText:'叫んだ人間を探す',jump:'search_screamer'},
      {text:'ぜんいんにこえをださせる',displayText:'全員に声を出させる',jump:'rollcall'},
      {text:'しずかにしてみみをすます',displayText:'静かにして耳を澄ます',jump:'listen_quiet'},
      {text:'でぐちにむかってにげる',displayText:'出口に向かって逃げる',jump:'run_exit'}
    ]
  },

  // ===== 叫んだ人間を探す =====
  {type:'text',label:'search_screamer',character:'ナレーション',
    text:'くらやみのなかをてさぐりですすむ。いすにつまずく。てーぶるにぶつかる。',
    displayText:'暗闇の中を手探りで進む。椅子につまずく。テーブルにぶつかる。'},
  {type:'text',character:'ナレーション',
    text:'てがだれかのかおにふれた。つめたい。うごかない。',
    displayText:'手が誰かの顔に触れた。冷たい。動かない。'},
  {type:'text',character:'ナレーション',
    text:'くちもとにてをあてる。いきをしていないようにかんじる。',
    displayText:'口元に手を当てる。息をしていないように感じる。'},
  {type:'text',character:'かとぱん',
    text:'どけおれがみる。えっとみゃくは。',
    displayText:'どけ俺が診る。えっと脈は……'},
  {type:'silence',duration:2000},
  {type:'text',character:'かとぱん',
    text:'ある。みゃくはある。きぜつしてるだけだ。たぶん。',
    displayText:'ある。脈はある。気絶してるだけだ。たぶん。'},
  {type:'text',character:'ナレーション',
    text:'たぶん。そのたぶんがくらやみではかぎりなくおもい。',
    displayText:'たぶん。その「たぶん」が暗闇では限りなく重い。'},
  {type:'flag',key:'found_body',value:true},
  {type:'jump',target:'who_fell'},

  // ===== 全員に声を出させる =====
  {type:'text',label:'rollcall',character:'ナレーション',
    text:'ぜんいんこえをだせとさけぶ。',
    displayText:'全員声を出せと叫ぶ。'},
  {type:'text',character:'ゆっきん',text:'ゆっきんここだ。',displayText:'ゆっきんここだ。'},
  {type:'text',character:'ちばぶ',text:'ちばぶいます。',displayText:'ちばぶいます。'},
  {type:'text',character:'デブコーン',text:'でぶこーんいるぞ。',displayText:'デブコーンいるぞ。'},
  {type:'text',character:'よっちん',text:'よっちんいるよ。',displayText:'よっちんいるよ。'},
  {type:'text',character:'かとぱん',text:'かとぱん。',displayText:'かとぱん。'},
  {type:'text',character:'エディマーシー',text:'えでぃまーしー。',displayText:'エディマーシー。'},
  {type:'text',character:'おちぷー',text:'おおちぷー。',displayText:'お、おちぷー。'},
  {type:'silence',duration:2000},
  {type:'text',character:'ゆっきん',
    text:'のぶんは。のぶんこえだせよ。',
    displayText:'のぶんは。のぶん声出せよ。'},
  {type:'silence',duration:2500},
  {type:'text',character:'ナレーション',
    text:'へんじがない。のぶんだけがこえをださない。',
    displayText:'返事がない。のぶんだけが声を出さない。'},
  {type:'flag',key:'found_body',value:false},
  {type:'jump',target:'who_fell'},

  // ===== 耳を澄ます =====
  {type:'text',label:'listen_quiet',character:'ナレーション',
    text:'しずかにしてとささやく。ぜんいんがくちをとじる。',
    displayText:'静かにして、と囁く。全員が口を閉じる。'},
  {type:'silence',duration:2500},
  {type:'text',character:'ナレーション',
    text:'きこえる。だれかのあらいいきづかい。そしてなにかをひきずるおと。',
    displayText:'聞こえる。誰かの荒い息遣い。そして何かを引きずる音。'},
  {type:'text',character:'ナレーション',
    text:'おとはへやのすみからきこえる。そしてゆっくりととおざかっていく。',
    displayText:'音は部屋の隅から聞こえる。そしてゆっくりと遠ざかっていく。'},
  {type:'text',character:'ナレーション',
    text:'どあがきしむおと。だれかがでていった。あるいはだれかがつれだされた。',
    displayText:'ドアが軋む音。誰かが出て行った。あるいは誰かが連れ出された。'},
  {type:'text',character:'ゆっきん',
    text:'おいいまどああいたよな。だれかでたのか。',
    displayText:'おい今ドア開いたよな。誰か出たのか。'},
  {type:'flag',key:'found_body',value:false},
  {type:'flag',key:'heard_drag',value:true},
  {type:'jump',target:'who_fell'},

  // ===== 逃げる =====
  {type:'text',label:'run_exit',character:'ナレーション',
    text:'やみのなかをはしる。まえもうしろもわからない。',
    displayText:'闇の中を走る。前も後ろも分からない。'},
  {type:'text',character:'ナレーション',
    text:'がんっ。',
    displayText:'ガンッ！'},
  {type:'text',character:'ナレーション',
    text:'かべにつよくぶつかった。あたまからなにかあたたかいものがつたう。',
    displayText:'壁に強くぶつかった。頭から何か温かいものが伝う。'},
  {type:'text',character:'おちぷー',
    text:'うわっだいじょうぶか!',
    displayText:'うわっ大丈夫か！'},
  {type:'text',character:'かとぱん',
    text:'おいうごくな。あたまからちでてるかもしれないぞ。',
    displayText:'おい動くな。頭から血出てるかもしれないぞ。'},
  {type:'text',character:'ナレーション',
    text:'いたみでうずくまる。くらやみのなかでむやみにうごくのはきけんだった。',
    displayText:'痛みでうずくまる。暗闇の中で無闇に動くのは危険だった。'},

  // ===== 選択肢3b =====
  {type:'choice',
    text:'けがをした。どうしますか。',
    displayText:'怪我をした。どうしますか？',
    choices:[
      {text:'かとぱんにてあてをたのむ',displayText:'かとぱんに手当てを頼む',jump:'ask_kato'},
      {text:'だれにもいわずたえる',displayText:'誰にも言わず耐える',jump:'endure'}
    ]
  },

  {type:'text',label:'ask_kato',character:'かとぱん',
    text:'きずをおさえて。おれがほうたいがわりになにかまく。',
    displayText:'傷を押さえて。俺が包帯代わりに何か巻く。'},
  {type:'text',character:'ナレーション',
    text:'かとぱんがぬののようなものをあたまにまいてくれた。ほんとうにいしゃのてつきなのかくらやみではわからない。',
    displayText:'かとぱんが布のようなものを頭に巻いてくれた。本当に医者の手つきなのか暗闇では分からない。'},
  {type:'flag',key:'injured',value:true},
  {type:'flag',key:'trust_kato',value:true},
  {type:'jump',target:'who_fell'},

  {type:'text',label:'endure',character:'ナレーション',
    text:'だまってきずぐちをおさえる。だれにもよわみをみせたくない。くらやみではよわいものからきえていくきがする。',
    displayText:'黙って傷口を押さえる。誰にも弱みを見せたくない。暗闇では弱い者から消えていく気がする。'},
  {type:'flag',key:'injured',value:true},
  {type:'flag',key:'trust_kato',value:false},
  {type:'jump',target:'who_fell'},

  // ===== のぶんが消えた =====
  {type:'text',label:'who_fell',character:'ナレーション',
    text:'こえをあつめるとひとつだけたりないこえがある。',
    displayText:'声を集めると一つだけ足りない声がある。'},
  {type:'text',character:'ゆっきん',
    text:'のぶん。のぶんへんじしろ。',
    displayText:'のぶん。のぶん返事しろ。'},
  {type:'silence',duration:2500},
  {type:'text',character:'ナレーション',
    text:'のぶんのこえだけがきこえない。',
    displayText:'のぶんの声だけが聞こえない。'},
  {type:'text',character:'おちぷー',
    text:'うそだろ。のぶん。おいのぶん!',
    displayText:'嘘だろ。のぶん。おいのぶん！'},
  {type:'text',character:'おちぷー',
    text:'ふざけんなよおおおっ!',
    displayText:'ふざけんなよぉぉぉっ！'},

  // ===== 選択肢4 =====
  {type:'choice',
    text:'のぶんがきえた。どうしますか。',
    displayText:'のぶんが消えた。どうしますか？',
    choices:[
      {text:'のぶんをさがしにいく',displayText:'のぶんを探しに行く',jump:'search_nobun'},
      {text:'ここにとどまってまつ',displayText:'ここに留まって待つ',jump:'stay_wait'}
    ]
  },

  // ===== のぶんを探す =====
  {type:'text',label:'search_nobun',character:'ナレーション',
    text:'くらやみをてさぐりですすむ。ゆかがぬるい。えきたいがふえている。',
    displayText:'暗闇を手探りで進む。床がぬるい。液体が増えている。'},
  {type:'text',character:'ナレーション',
    text:'すみのほうでなにかにてがふれた。にんげんのからだだ。うごかない。',
    displayText:'隅の方で何かに手が触れた。人間の体だ。動かない。'},
  {type:'text',character:'ナレーション',
    text:'くびもとにてをあてる。みゃくがよわいがある。いきはしてる。',
    displayText:'首元に手を当てる。脈が弱いがある。息はしてる。'},
  {type:'text',character:'ナレーション',
    text:'しかしあたまのあたりがぬれている。それがなんのえきたいかはくらやみではわからない。',
    displayText:'しかし頭の辺りが濡れている。それが何の液体かは暗闇では分からない。'},

  // ===== 選択肢5 =====
  {type:'choice',
    text:'のぶんをみつけた。どうしますか。',
    displayText:'のぶんを見つけた。どうしますか？',
    choices:[
      {text:'みんなのところにはこぶ',displayText:'みんなの所に運ぶ',jump:'carry_nobun'},
      {text:'かとぱんをよびにいく',displayText:'かとぱんを呼びに行く',jump:'call_kato'}
    ]
  },

  {type:'text',label:'carry_nobun',character:'ナレーション',
    text:'おもいからだをひきずるようにはこぶ。くらやみでどこにむかっているかもわからない。',
    displayText:'重い体を引きずるように運ぶ。暗闇でどこに向かっているかも分からない。'},
  {type:'text',character:'デブコーン',
    text:'おいなんのおとだ。なにかひきずってんのか。',
    displayText:'おいなんの音だ。何か引きずってんのか。'},
  {type:'text',character:'ナレーション',
    text:'のぶんをみんなのちかくにおろした。',
    displayText:'のぶんをみんなの近くに下ろした。'},
  {type:'flag',key:'nobun_moved',value:true},
  {type:'jump',target:'knife_sound'},

  {type:'text',label:'call_kato',character:'ナレーション',
    text:'かとぱんきてくれとさけぶ。しかしこえがかえってこない。',
    displayText:'かとぱん来てくれと叫ぶ。しかし声が返ってこない。'},
  {type:'text',character:'よっちん',
    text:'かとぱんならさっきべつのほうにいったぜ。',
    displayText:'かとぱんならさっき別の方に行ったぜ。'},
  {type:'text',character:'ナレーション',
    text:'かとぱんはいない。のぶんのそばでひとりきりだ。',
    displayText:'かとぱんはいない。のぶんのそばで一人きりだ。'},
  {type:'flag',key:'nobun_moved',value:false},
  {type:'jump',target:'knife_sound'},

  // ===== 留まる =====
  {type:'text',label:'stay_wait',character:'ナレーション',
    text:'うごかない。うごいたらしぬ。そんなきがする。',
    displayText:'動かない。動いたら死ぬ。そんな気がする。'},
  {type:'text',character:'ちばぶ',
    text:'にんげんはきょうふをかんじるとからだがこわばってうごけなくなる。とうそうはんのうのいっしゅだよ。',
    displayText:'人間は恐怖を感じると体が強ばって動けなくなる。逃走反応の一種だよ。'},
  {type:'text',character:'ゆっきん',
    text:'ちばぶおまえよくそんなれいせいでいられるな。',
    displayText:'ちばぶお前よくそんな冷静でいられるな。'},
  {type:'text',character:'ちばぶ',
    text:'れいせいじゃないよ。ふるえてる。ただしっていることをはなすとおちつくんだ。',
    displayText:'冷静じゃないよ。震えてる。ただ知っていることを話すと落ち着くんだ。'},
  {type:'flag',key:'nobun_moved',value:false},
  {type:'jump',target:'knife_sound'},

  // ===== 包丁の音 =====
  {type:'text',label:'knife_sound',character:'ナレーション',
    text:'しずけさのなかにかすかなきんぞくおんがひびいた。',
    displayText:'静寂の中にかすかな金属音が響いた。'},
  {type:'silence',duration:600},
  {type:'text',character:'ナレーション',
    text:'しゃりっ、しゃりっ。',
    displayText:'シャリッ、シャリッ……'},
  {type:'text',character:'ナレーション',
    text:'ほうちょうをとぐようなおと。だれかがやみのなかではものをもっている。',
    displayText:'包丁を研ぐような音。誰かが闇の中で刃物を持っている。'},
  {type:'text',character:'おちぷー',
    text:'ひっ!',
    displayText:'ひっ！'},
  {type:'text',character:'おちぷー',
    text:'いまなんのおとだよ。なんかこすれるおとしなかったか。',
    displayText:'今何の音だよ。なんか擦れる音しなかったか。'},
  {type:'text',character:'デブコーン',
    text:'あわりい。おれのほうちょうだ。りょうりのじゅんびしてて。',
    displayText:'あ、悪い。俺の包丁だ。料理の準備してて。'},
  {type:'text',character:'ゆっきん',
    text:'このじょうきょうでりょうりすんのかよ。あたまおかしいんじゃねえの。',
    displayText:'この状況で料理すんのかよ。頭おかしいんじゃねえの。'},
  {type:'text',character:'デブコーン',
    text:'くうもんつくるのがおれのしごとだ。てがあいてりゃつくるにきまってる。',
    displayText:'食うもん作るのが俺の仕事だ。手が空いてりゃ作るに決まってる。'},

  // ===== 選択肢6 =====
  {type:'choice',
    text:'くらやみでほうちょうをもっている。どうしますか。',
    displayText:'暗闘で包丁を持っている。どうしますか？',
    choices:[
      {text:'ほうちょうをわたせという',displayText:'包丁を渡せと言う',jump:'take_knife'},
      {text:'すきにさせる',displayText:'好きにさせる',jump:'let_cook'}
    ]
  },

  {type:'text',label:'take_knife',character:'デブコーン',
    text:'はあ? おれをうたがってんのかよ。わかったよほら。',
    displayText:'はあ？俺を疑ってんのかよ。分かったよほら。'},
  {type:'text',character:'ナレーション',
    text:'くらやみでほうちょうをうけとる。やいばのほうこうがわからない。',
    displayText:'暗闇で包丁を受け取る。刃の方向が分からない。'},
  {type:'text',character:'ナレーション',
    text:'ざくっ。',
    displayText:'ザクッ。'},
  {type:'text',character:'ナレーション',
    text:'てのひらにするどいいたみがはしった。てがきれた。ちがしたたる。くらやみではじぶんのちすらみえない。',
    displayText:'手のひらに鋭い痛みが走った。手が切れた。血が滴る。暗闇では自分の血すら見えない。'},
  {type:'flag',key:'has_knife',value:true},
  {type:'flag',key:'hand_cut',value:true},
  {type:'jump',target:'debu_cooking'},

  {type:'text',label:'let_cook',character:'ナレーション',
    text:'すきにさせた。くらやみでほうちょうのおとがつづく。',
    displayText:'好きにさせた。暗闇で包丁の音が続く。'},
  {type:'text',character:'ナレーション',
    text:'とんとんとんとん。',
    displayText:'トントントントン。'},
  {type:'text',character:'ナレーション',
    text:'なにかをきざんでいる。それがやさいなのかにくなのかそれとも。くらやみではわからない。',
    displayText:'何かを刻んでいる。それが野菜なのか肉なのかそれとも……暗闇では分からない。'},
  {type:'flag',key:'has_knife',value:false},
  {type:'flag',key:'hand_cut',value:false},
  {type:'jump',target:'debu_cooking'},

  // ===== デブコーンの料理 =====
  {type:'text',label:'debu_cooking',character:'ナレーション',
    text:'しばらくしてさらをさしだしてきた。',
    displayText:'しばらくして皿を差し出してきた。'},
  {type:'text',character:'デブコーン',
    text:'ほらくえよ。くらやみでもあじはわかるだろ。',
    displayText:'ほら食えよ。暗闇でも味は分かるだろ。'},
  {type:'text',character:'ナレーション',
    text:'さらのうえになにかがのっている。あたたかい。においはにくのようでもありさかなのようでもある。',
    displayText:'皿の上に何かが乗っている。温かい。匂いは肉のようでもあり魚のようでもある。'},

  // ===== 選択肢7（カウントダウン） =====
  {type:'choice',
    text:'でぶこーんのりょうりをたべますか。',
    displayText:'デブコーンの料理を食べますか？',
    countdown:10,
    timeoutJump:'timeout_eat',
    choices:[
      {text:'たべる',displayText:'食べる',jump:'eat_food'},
      {text:'ぜったいにたべない',displayText:'絶対に食べない',jump:'refuse_food'}
    ]
  },

  {type:'text',label:'timeout_eat',character:'ナレーション',
    text:'まよっているあいだにだれかがくちにおしこんできた。',
    displayText:'迷っている間に誰かが口に押し込んできた。'},
  {type:'text',character:'ナレーション',
    text:'うっ。',
    displayText:'うっ……'},
  {type:'text',character:'ナレーション',
    text:'あじがひろがる。なにかのにく。しかしなんのにくかはわからない。',
    displayText:'味が広がる。何かの肉。しかし何の肉かは分からない。'},
  {type:'flag',key:'ate_food',value:true},
  {type:'jump',target:'after_food'},

  {type:'text',label:'eat_food',character:'ナレーション',
    text:'くちにいれた。かんだ。やわらかいにく。あじつけはしおとなにか。',
    displayText:'口に入れた。噛んだ。柔らかい肉。味付けは塩と何か。'},
  {type:'text',character:'ナレーション',
    text:'うまい。おそろしいほどうまい。しかしこれがなんのにくなのかだれもしらない。',
    displayText:'美味い。恐ろしいほど美味い。しかしこれが何の肉なのか誰も知らない。'},
  {type:'flag',key:'ate_food',value:true},
  {type:'jump',target:'after_food'},

  {type:'text',label:'refuse_food',character:'デブコーン',
    text:'くわねえのか。もったいねえな。',
    displayText:'食わねえのか。もったいねえな。'},
  {type:'text',character:'ナレーション',
    text:'さらをはらった。なかみがゆかにおちる。べちゃっ。',
    displayText:'皿を払った。中身が床に落ちる。べちゃっ。'},
  {type:'flag',key:'ate_food',value:false},
  {type:'jump',target:'after_food'},

  // ===== 食後 =====
  {type:'text',label:'after_food',character:'ナレーション',
    text:'そのときへやのおくからうなりごえがきこえた。',
    displayText:'その時、部屋の奥から唸り声が聞こえた。'},
  {type:'silence',duration:500},
  {type:'text',character:'ナレーション',
    text:'うううう。',
    displayText:'ウウウウ……'},
  {type:'text',character:'ナレーション',
    text:'にんげんのこえかけもののこえかくらやみではくべつがつかない。',
    displayText:'人間の声か獣の声か暗闇では区別がつかない。'},
  {type:'text',character:'よっちん',
    text:'なあおれたちほんとうにはちにんだけなのか。',
    displayText:'なあ俺たち本当に八人だけなのか。'},
  {type:'text',character:'ちばぶ',
    text:'さいしょのてんこではちにんいた。でもくらやみになってからはだれがどこにいるかだれにもわからない。',
    displayText:'最初の点呼で八人いた。でも暗闇になってからは誰がどこにいるか誰にも分からない。'},

  // ===== 選択肢8 =====
  {type:'choice',
    text:'うなりごえがきこえる。どうしますか。',
    displayText:'唸り声が聞こえる。どうしますか？',
    choices:[
      {text:'うなりごえのほうにいく',displayText:'唸り声の方に行く',jump:'go_growl'},
      {text:'にげるじゅんびをする',displayText:'逃げる準備をする',jump:'prep_escape'}
    ]
  },

  {type:'text',label:'go_growl',character:'ナレーション',
    text:'おとのするほうへすすむ。うなりごえがおおきくなる。ちかい。すぐめのまえにいる。',
    displayText:'音のする方へ進む。唸り声が大きくなる。近い。すぐ目の前にいる。'},
  {type:'text',character:'ナレーション',
    text:'てがなにかにふれた。にんげんのかみのけ。しかしぬれている。べっとりと。',
    displayText:'手が何かに触れた。人間の髪の毛。しかし濡れている。べっとりと。'},
  {type:'text',character:'ナレーション',
    text:'そのにんげんがうでをつかんできた。つよいちからで。',
    displayText:'その人間が腕を掴んできた。強い力で。'},

  // ===== 選択肢9（カウントダウン） =====
  {type:'choice',
    text:'うでをつかまれた。どうしますか。',
    displayText:'腕を掴まれた。どうしますか？',
    countdown:5,
    timeoutJump:'grabbed_timeout',
    choices:[
      {text:'ふりほどく',displayText:'振りほどく',jump:'shake_off'},
      {text:'だれなのかきく',displayText:'誰なのか聞く',jump:'ask_who'}
    ]
  },

  {type:'text',label:'grabbed_timeout',character:'ナレーション',
    text:'うでをつかまれたままひきずられていく。くらやみのおくへ。',
    displayText:'腕を掴まれたまま引きずられていく。暗闇の奥へ。'},
  {type:'text',character:'ナレーション',
    text:'たすけてくれえええっ!',
    displayText:'助けてくれぇぇぇっ！'},
  {type:'gameover'},

  {type:'text',label:'shake_off',character:'ナレーション',
    text:'ちからいっぱいふりほどいた。あいてはよろめいたようだ。にげるようにもとのばしょにもどる。',
    displayText:'力いっぱい振りほどいた。相手はよろめいたようだ。逃げるように元の場所に戻る。'},
  {type:'flag',key:'shook_off',value:true},
  {type:'jump',target:'chapter1_end'},

  {type:'text',label:'ask_who',character:'ナレーション',
    text:'だれだとさけんだ。こたえはない。ただうなりごえだけがきこえる。',
    displayText:'誰だと叫んだ。答えはない。ただ唸り声だけが聞こえる。'},
  {type:'text',character:'ナレーション',
    text:'おい、だれなんだよっ!',
    displayText:'おい、誰なんだよっ！'},
  {type:'text',character:'ナレーション',
    text:'そしてゆっくりとてがはなされた。あいてがだれだったのかはわからないまま。',
    displayText:'そしてゆっくりと手が離された。相手が誰だったのかは分からないまま。'},
  {type:'flag',key:'shook_off',value:false},
  {type:'jump',target:'chapter1_end'},

  {type:'text',label:'prep_escape',character:'ナレーション',
    text:'かべぞいにすすんででぐちをさがす。どあをみつけた。しかしかぎがかかっている。',
    displayText:'壁沿いに進んで出口を探す。ドアを見つけた。しかし鍵がかかっている。'},
  {type:'text',character:'エディマーシー',
    text:'おもてのどあはおれがしめたときかぎかけてねえぞ。だれかがうちがわからかぎをかけたんだ。',
    displayText:'表のドアは俺が閉めた時鍵かけてねえぞ。誰かが内側から鍵をかけたんだ。'},
  {type:'text',character:'ナレーション',
    text:'とじこめられている。このくらやみのなかに。',
    displayText:'閉じ込められている。この暗闇の中に。'},

  // ===== 選択肢10 =====
  {type:'choice',
    text:'かぎがかかっている。どうしますか。',
    displayText:'鍵がかかっている。どうしますか？',
    choices:[
      {text:'ちからずくでこわす',displayText:'力ずくで壊す',jump:'break_door'},
      {text:'かぎをかけたやつをさがす',displayText:'鍵をかけた奴を探す',jump:'find_locker'}
    ]
  },

  {type:'text',label:'break_door',character:'ナレーション',
    text:'どあにたいあたりする。びくともしない。',
    displayText:'ドアに体当たりする。びくともしない。'},
  {type:'text',character:'ナレーション',
    text:'どんっ。どんっ。どんっ。',
    displayText:'ドンッ！ドンッ！ドンッ！'},
  {type:'text',character:'ナレーション',
    text:'なんどもぶつかる。かたがきしむ。それでもあかない。',
    displayText:'何度もぶつかる。肩が軋む。それでも開かない。'},
  {type:'text',character:'ゆっきん',
    text:'やめろ。むだだ。それよりなかのやつをなんとかするほうがさきだ。',
    displayText:'やめろ無駄だ。それより中の奴をなんとかする方が先だ。'},
  {type:'flag',key:'tried_break',value:true},
  {type:'jump',target:'chapter1_end'},

  {type:'text',label:'find_locker',character:'ナレーション',
    text:'だれかがかぎをかけた。それはこのなかのだれかだ。',
    displayText:'誰かが鍵をかけた。それはこの中の誰かだ。'},
  {type:'text',character:'よっちん',
    text:'かぎをかけるにはかぎがいる。つまりだれかがこのみせのかぎをもってるってことだ。',
    displayText:'鍵をかけるには鍵がいる。つまり誰かがこの店の鍵を持ってるってことだ。'},
  {type:'text',character:'ナレーション',
    text:'おさななじみのなかにはんにんがいる。そのじじつがくらやみのなかでおもくのしかかる。',
    displayText:'幼馴染の中に犯人がいる。その事実が暗闇の中で重くのしかかる。'},
  {type:'flag',key:'tried_break',value:false},
  {type:'jump',target:'chapter1_end'},

  // ===== 第一章終了 =====
  {type:'text',label:'chapter1_end',character:'ナレーション',
    text:'くらやみはつづく。だれもたすけはこない。そしてまだよるはながい。',
    displayText:'暗闇は続く。誰も助けは来ない。そして、まだ夜は長い。'},
  {type:'silence',duration:2000},
  {type:'text',character:'ナレーション',
    text:'だいいっしょうしゅうりょう。',
    displayText:'第一章　終了'},
  {type:'silence',duration:2000},
  {type:'end'}
];
Chapter1Script.chapterTitle='第一章：暗闇の始まり';
